# Proxy configuration
proxy:
  enabled: false
  http: "http://10.0.0.1:3128"
  https: "http://10.0.0.1:3128"
  noProxy: "localhost,127.0.0.1,.svc.cluster.local"

# Registry settings
registry:
  url: "harbor.example.com/tenant"
  pullSecret: "harbor-creds"

# Schedule for monthly scan
scan:
  schedule: "0 4 1 * *"   # At 04:00 on day 1 of every month
  timezone: "Asia/Kolkata"

# List of tools and their images/args
tools:
  - name: kube-bench
    image: "aquasec/kube-bench:latest"
    args:
      - "--json"
      - "--output"
      - "/reports/kube-bench-{{workflow.creationTimestamp}}.json"
  - name: falco
    image: "falcosecurity/falco:latest"
    args:
      - "--driver"
      - "json"
      - "--json-output"
      - "/reports/falco-{{workflow.creationTimestamp}}.json"
  - name: anchore
    image: "harbor.example.com/tenant/anchore-cli:latest"
    args:
      - "/bin/sh"
      - "-c"
      - >-
        anchore-cli --u $ANCH_USER --p $ANCH_PASS image add my-registry/app:latest &&
        anchore-cli image wait my-registry/app:latest &&
        anchore-cli image vuln my-registry/app:latest all > /reports/anchore-{{workflow.creationTimestamp}}.json
  - name: nessus
    image: "harbor.example.com/tenant/nessus:latest"
    args:
      - "/bin/sh"
      - "-c"
      - >-
        nessuscli --host $NESSUS_HOST --username $NESSUS_USER --password $NESSUS_PASS \
          --scan-policy 'K8s-Vuln' --target my-registry/app:latest \
          --format html --output /reports/nessus-{{workflow.creationTimestamp}}.html
  - name: mde-linux
    image: "mcr.microsoft.com/mde/linux:latest"
    args:
      - "/bin/sh"
      - "-c"
      - >-
        mde-agent --tenant $MDE_TENANT_ID --workload $MDE_WORKLOAD_ID \
          --output /reports/mde-{{workflow.creationTimestamp}}.json
  - name: invicti
    image: "harbor.example.com/tenant/invicti-scanner:latest"
    args:
      - "/bin/sh"
      - "-c"
      - >-
        invicti-cli scan --target https://app.example.com \
          --format json --output /reports/invicti-{{workflow.creationTimestamp}}.json
  - name: nmap
    image: "instrumentisto/nmap:latest"
    args:
      - "-sV"
      - "app-service.security-scans.svc.cluster.local"
      - ">"
      - "/reports/nmap-{{workflow.creationTimestamp}}.txt"
  - name: t50
    image: "corfr/t50:latest"
    args:
      - "--flood"
      - "--destport"
      - "80"
      - "app-service.security-scans.svc.cluster.local"
      - ">"
      - "/reports/t50-{{workflow.creationTimestamp}}.txt"
