{{- if not (lookup "apiextensions.k8s.io/v1" "CustomResourceDefinition" "cronworkflows.argoproj.io") }}
# Install Argo Workflows controller from Helm chart
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argo-workflows
  namespace: {{ .Release.Namespace }}
spec:
  interval: 1h
  chart:
    spec:
      chart: argo-workflows
      sourceRef:
        kind: HelmRepository
        name: argo-workflows-repo
  values:
    controller:
      containerRuntimeExecutor: "kubernetes-api"
      workflowDefaults:
        ttlStrategy:
          secondsAfterFinished: 3600
{{- end }}
